# Postgres profile
spring.datasource.url=jdbc:postgresql://localhost:5433/pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase Configuration for Database Schema Management
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.liquibase-tablespace=public
spring.liquibase.drop-first=false
spring.liquibase.validate-on-migrate=true
spring.liquibase.contexts=dev
spring.liquibase.label-filter=dev
